### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by Capossito** [osamaq/react-native-image-colors#6]
I'm getting this error, tried to debug but no success, any help? iOS works fine btw

Error: ImageColors: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference

System:
    OS: macOS 10.15.4
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 
    Yarn: 1.13.0
    npm: 6.13.4 
  Managers:
    CocoaPods: 1.9.1 
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 16, 19, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 30.0.1
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c
  Languages:
    Java: 1.8.0_201 
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2

**Comment by osamaq** [comment]
Sorry about that. I think its because you omitted `config` object when calling `getColors(uri, config)`,

But all the keys in that object are optional, so it makes sense that it should work without it.
Just released [v1.2.3](https://github.com/osamaq/react-native-image-colors/releases/tag/v1.2.3) which should fix it.

Thanks for the report and let me know if it works for you now.

**Comment by Capossito** [comment]
sure ill check with the new fix, however, I passed the config with fallback and was still getting the error. But will give it a try now. thanks.
